### ISSUE TITLE
develop intruduced a problem when inputting strings: text field doesn't stay active, so only captures one character

### ISSUE THREAD

**Issue by Gaai** [sbrin/lopaka#129] opened 2024-02-25 21:31 UTC
When entering a string and trying to edit the text field, the form field loses 'focus'/'active' status after one or sometimes two typed characters. Focus/active status goes to the preview element. When you try to remove multiple characters it removes one and then removes the whole string, because of this. Tried on different browsers: chrome, brave, edge.

**Comment by deadlink** [comment] 2024-02-25 21:56
@Gaai Could you provide more information please? I can't reproduce

**Comment by deadlink** [comment] 2024-02-25 22:10
Fixed in #131

**Comment by sbrin** [comment] 2024-02-26 05:19
thank you

**Closed by sbrin** 2024-02-26 05:19 UTC
Labels: bug
